### ISSUE TITLE
Running generate gives "Can't use an undefined value as an ARRAY reference"

### ISSUE THREAD

**Issue by jakkdl** [mschout/toggl-invoicer#8]
Hello!

I'm on the hunt for an invoice generator from toggl data, and this project looked like it was perfect for the job! I got it built, configured it, and got both `list-clients` and `list-workspaces` to work without any issues. But trying to run `generate` consistently gives the error:
```
Can't use an undefined value as an ARRAY reference at /app/lib/App/TogglInvoicer/Command/Generate.pm line 210.
```
Lines in question being
https://github.com/mschout/toggl-invoicer/blob/cebd0af60a0e3ef2e7a9e00145829abdaca504e1/lib/App/TogglInvoicer/Command/Generate.pm#L195-L213

After debugging it for a while I came to the not too surprising conclusion that the error is probably that it doesn't find any reports/time entries. After further digging I thought it might be me not having generated reports, instead of fetching [raw time entries](https://developers.track.toggl.com/docs/api/time_entries), so I upgraded to the "starter" billing plan and generated a couple reports in the relevant date ranges - but that failed to make any difference.
Given that there's recent activity in this repository, I felt it shouldn't be a case of using an outdated API or similar, but I with very limited perl skills I'm getting stumped on how to continue and would love some help~

Thanks!

**Comment by mschout** [comment]
Hi @jakkdl thanks for the report.  Didn't know anyone outside my own org was using this :)  I will take a look today and hopefully get it figured out.

**Comment by mschout** [comment]
FWIW, we're all using this on the "free" plan so it should work no matter what plan you are on.

**Comment by mschout** [comment]
Hi @jakkdl finally took a quick look at this, and the only way I am able to get it to error out like this is if I have given it the wrong workspace id, so you should make sure that you have given the correct workspace id.

I have fixed it so that it will not crash if this happens however.  Will be pushing updated docker image (v0.5.1) shortly.

**Comment by mschout** [comment]
I have no idea what caused that either, but it is happening where it asks toggl for the detailed report, and the error actually comes from within `WebService::Toggl` itself, which, AFAIK, has no error reporting mechanism so I am not sure what could be done about it.

If you got an invoice without entries, and no errors were produced, most likely you have the wrong client id.

**Comment by mschout** [comment]
Best we could likely do is say something like "Failed to get detailed report from Toggl" or something.

**Comment by jakkdl** [comment]
Makes sense. Thanks again for the fix! Will generate an invoice and send soon and looking forward to making use of this :)
